name: ffa_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  context_watch: ^4.0.0
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.2.2
  flutter_syntax_view: ^4.1.0
  go_router: ^14.2.1
  http: ^1.2.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  collection: ^1.18.0

dependency_overrides: 
  shared_preferences_web: ^2.4.0
  url_launcher_web: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/
