name: ffa_server
description: Simple multi-tenant analytics server
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  crypto: ^3.0.3
  dart_mappable: ^4.2.2
  dotenv: ^4.2.0
  nanoid2: ^2.0.1
  path: ^1.9.0
  shelf_router: ^1.1.4
  shelf: ^1.4.2
  sqlite3: ^2.4.5
  shelf_helmet: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  lints: ^3.0.0
  test: ^1.24.0
